language: node_js
node_js:
  - "4.4.3"
services:
  - mongodb
before-script:
  - npm install
script:
  - npm run lint
  - npm test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8
